Update to neo 5 junit 5
Xceptance/neodymium-example pull request #26
Opened 2024-06-25 11:43 UTC by kqmpetenz

2024-06-25 14:16 UTC, wurzelkuchen requested changes

2024-06-26 11:13 UTC, kqmpetenz commented on pom.xml
> +  <version>4.1.0-SNAPSHOT</version>
did it

2024-06-26 11:13 UTC, kqmpetenz commented on pom.xml
> +    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
did it

2024-07-17 08:19 UTC, wurzelkuchen approved these changes

2024-07-17 08:20 UTC, merged